### ISSUE TITLE
Sample description no longer appears with mouse hover

### ISSUE THREAD

**Issue by hoogerheide** [reductus/reductus#105]
Hovering the pointer above a data file used to display a tooltip with its description. This apparently no longer works. Is it supposed to, or is this no longer a feature? It was quite useful.

**Comment by bmaranville** [comment]
I think it got lost when the file tree was refactored.  I will see if I can revive it!

**Comment by bmaranville** [comment]
Closed by fbfedabef76792020b9577ee2e39c2ab5cb32d32
