### ISSUE TITLE
mask selector doesn't work

### ISSUE THREAD

**Issue by hoogerheide** [reductus/reductus#109]
The radio buttons for "zoom", "select", and "deselect" in the "Mask" module don't work; they only zoom.

**Comment by bmaranville** [comment]
!?  This is unexpected.  It's still working on the deployed reductus.nist.gov so it's a recent change!

**Comment by bmaranville** [comment]
I found the problem... I had changed the element the zoom function was bound to, and it was then "higher" than the element the interactors are bound to, so zoomRect was intercepting all the mouse drag events.
