### ISSUE TITLE
Can't normalize to monitor when any monitor value is zero

### ISSUE THREAD

**Issue by hoogerheide** [reductus/reductus#56]
When containing points where monitor counts are zero, data files cannot be normalized by monitor and passed onto further modules (like "mask", which could be used to get rid of such points).

See, for example, https://ncnr.nist.gov/ncnrdata/view/nexus-zip-viewer.html?pathlist=ncnrdata+magik+201907+26391+data&filename=mw02619848.nxz.cgd

**Comment by pkienzle** [comment]
This is now fixed.  I also fixed normalization by reactor power and normalization by roi, not that anyone will ever need these.
