### ISSUE TITLE
NaN in 2d plots

### ISSUE THREAD

**Issue by hoogerheide** [reductus/reductus#93]
When mousing over a 2D plot, the third coordinate is always listed as NaN. If it is possible to tie this to the actual value of the pixel, this would be very useful.

**Comment by bmaranville** [comment]
This is a good point.  This was set up for the old 2d plotter, but recently everything got shifted to the 2d multi plotter and I suspect that it when it was broken.

**Comment by bmaranville** [comment]
Hah - this turns out to have been an issue with the fact that our x-axis goes from high to low.  Other than that i think it's working fine.  (comparisons with xmax and xmin from dims were nonsensical)
Will fix.

**Comment by bmaranville** [comment]
fixed by release https://github.com/usnistgov/d3-science/releases/tag/v0.2.7
